### ISSUE TITLE
unknown keywords: :whitelist_classes, :whitelist_symbols

### ISSUE THREAD

**Issue by ewlarson** [geoblacklight/geoblacklight_sidecar_images#23]
Running rails console from template app:

```bash
beans:.internal_test_app ewlarson$ bundle exec rails console
Traceback (most recent call last):
	24: from bin/rails:4:in `<main>'
	23: from bin/rails:4:in `require'
	22: from /Users/ewlarson/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-5.2.4.4/lib/rails/commands.rb:18:in `<top (required)>'
	21: from /Users/ewlarson/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-5.2.4.4/lib/rails/command.rb:46:in `invoke'
	20: from /Users/ewlarson/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-5.2.4.4/lib/rails/command/base.rb:69:in `perform'
	19: from /Users/ewlarson/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	18: from /Users/ewlarson/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	17: from /Users/ewlarson/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	16: from /Users/ewlarson/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-5.2.4.4/lib/rails/commands/console/console_command.rb:95:in `perform'
	15: from /Users/ewlarson/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-5.2.4.4/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
	14: from /Users/ewlarson/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-5.2.4.4/lib/rails/command/actions.rb:22:in `require_application!'
	13: from /Users/ewlarson/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-5.2.4.4/lib/rails/command/actions.rb:22:in `require'
	12: from /Users/ewlarson/Rails/geoblacklight_sidecar_images/.internal_test_app/config/application.rb:18:in `<top (required)>'
	11: from /Users/ewlarson/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.8/lib/bundler.rb:173:in `require'
	10: from /Users/ewlarson/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.8/lib/bundler/runtime.rb:50:in `require'
	 9: from /Users/ewlarson/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.8/lib/bundler/runtime.rb:50:in `each'
	 8: from /Users/ewlarson/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.8/lib/bundler/runtime.rb:61:in `block in require'
	 7: from /Users/ewlarson/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.8/lib/bundler/runtime.rb:61:in `each'
	 6: from /Users/ewlarson/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.8/lib/bundler/runtime.rb:66:in `block (2 levels) in require'
	 5: from /Users/ewlarson/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.8/lib/bundler/runtime.rb:66:in `require'
	 4: from /Users/ewlarson/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-rspec-1.30.1/lib/rubocop-rspec.rb:24:in `<top (required)>'
	 3: from /Users/ewlarson/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-rspec-1.30.1/lib/rubocop/rspec/inject.rb:8:in `defaults!'
	 2: from /Users/ewlarson/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-0.60.0/lib/rubocop/config_loader.rb:159:in `load_yaml_configuration'
	 1: from /Users/ewlarson/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-0.60.0/lib/rubocop/config_loader.rb:185:in `yaml_safe_load'
/Users/ewlarson/.rbenv/versions/2.7.2/lib/ruby/2.7.0/psych.rb:328:in `safe_load': unknown keywords: :whitelist_classes, :whitelist_symbols (ArgumentError)
```

**Comment by ewlarson** [comment]
Seems related to using an outdated rubocop.
